ID=v56
MYSQL_HOME=/home/mysql/release/5.6.25-ndb-7.4.7

#ID=v55
#MYSQL_HOME=/home/mysql/release/5.5.32

#ID=v51
#MYSQL_HOME=/home/mysql/release/5.1.70

#ID=v50
#MYSQL_HOME=/home/mysql/release/5.0.96

#ID=v41
#MYSQL_HOME=/home/mysql/release/4.1.25

#ID=v40
#MYSQL_HOME=/home/mysql/release/4.0.30
